package ${basePackage};

import ${basePackage}.repository.entity.${model};
import javax.validation.constraints.*;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.google.common.base.MoreObjects;

/*
 * Generated by CodeSketch http://vnzmi.com
 * at ${TIME}
 */
public class ${model}Dto {

<#list fields as field>
/**
 * ${field.guessedTitle}
 */
<#list field.java.validators as validator>
        ${validator}
</#list>
<#if field.created >
@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
</#if>
private ${field.java.type} ${field.nameCamel};
</#list>

public ${model}Dto(){}

public ${model}Dto(${model} item)
        {
<#list fields as field>
        ${field.nameCamel} = item.${field.java.getter}();
</#list>
        }

<#list fields as field>
public ${field.java.type} ${field.java.getter}() {
        return ${field.nameCamel};
        }
</#list>

<#list fields as field>
public  ${field.java.setter}(${field.java.type} value ) {
        this.${field.nameCamel} = value;
        }
</#list>

public String toString()
        {
        return MoreObjects.toStringHelper(this)
<#list fields as field>
        .add("${field.nameCamel}",${field.java.getter}())
</#list>
        .toString();
        }
        }
