package ${basePackage}.dto;

import ${basePackage}.repository.entity.${model};
import javax.validation.constraints.*;
import java.util.Date;
import lombok.Data;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/*
* Generated by CodeSketch http://vnzmi.com
* at ${TIME}
*/
@Data
public class ${model}Dto {

    <#list fields as field>
    /**
     * ${field.guessedTitle}
     */
    <#list field.java.validators as validator>
    ${validator}
    </#list>
    <#if field.java.type == "Date" && field.deleted == false >
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    </#if>
    <#if field.deleted >
    @JsonIgnore
    </#if>
    private ${field.java.typeObject} ${field.nameCamel} ${field.java.defaultExpression};
    </#list>
    
    public ${model}Dto(){}

    public ${model}Dto(${model} item)
    {
        <#list fields as field>
        ${field.nameCamel} = item.${field.java.getter}();
        </#list>
    }
}
