package ${basePackage}.model;

import ${basePackage}.repository.entity.${model};
import javax.validation.constraints.*;
import java.util.Date;
import lombok.Data;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/*
* Generated by CodeSketch http://vnzmi.com
* at ${TIME}
*/
@Data
@ApiModel("${tableInfo.comment}传输对象")
public class ${model}DTO{

    <#list fields as field>
    /**
    * ${field.guessedTitle}
    */
    <#if field.primaryKey == true >
        <#continue>
    </#if>
    <#list field.java.validators as validator>
    ${validator}
    </#list>
    
    <#if field.java.type=="Date"&&field.deleted==false>@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")</#if><#if field.deleted>@JsonIgnore</#if>
    @ApiModelProperty("${field.guessedTitle}")
    private ${field.java.typeObject} ${field.nameCamel} ${field.java.defaultExpression};
    </#list>

    public ${model}DTO (){} 
 
    public ${model}DTO (${model} entity)

    {
        <#list fields as field>
        <#if field.primaryKey == true >
        <#continue>
        </#if>
        ${field.nameCamel} = entity.${field.java.getter}();
        </#list>
    }
}
