package ${basePackage}.model;

import ${basePackage}.repository.entity.${model};
import java.util.Date;
import lombok.Data;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/*
* Generated by CodeSketch http://vnzmi.com
* at ${TIME}
*/
@Data
@ApiModel("${tableInfo.comment}显示对象")
public class ${model}VO{

    <#list fields as field>
    /**
    * ${field.guessedTitle}
    */
    <#if field.java.type=="Date"&&field.deleted==false>@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")</#if><#if field.deleted>@JsonIgnore</#if>
    @ApiModelProperty("${field.guessedTitle}")
    private ${field.java.typeObject} ${field.nameCamel} ${field.java.defaultExpression};
    </#list>

    public ${model}VO (){} 
 
    public ${model}VO (${model} entity)
    {
        <#list fields as field>
        ${field.nameCamel} = entity.${field.java.getter}();
        </#list>
    }
}
